name: cicd2
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repository
        uses: actions/checkout@v4.1.5
      - name: list files
        run: ls -l
      - name: Installing Java 11 on the runner machine
        uses: actions/setup-java@v4.2.1
        with: 
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: verify java
        run: java -version
      - name: build to be done
        run: |
           mvn package
           ls -l
           ls -l ./target
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Create docker image and container
        run: |
           docker build . --file Dockerfile -t newimage:v1
           docker images
           docker run -dt --name c1 --hostname c1 newimage:v1
           docker ps -a

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  
      - name: Docker push
        run: |
          docker tag newimage:${{ GITHUB.RUN_NUMBER }} niran736/inte5:${{ GITHUB.RUN_NUMBER }}
          docker tag myimage:${{ GITHUB.RUN_NUMBER }} niran736/intel5:tagname
          docker push niran736/intel5:tagname
          docker push niran736/intel5:${{ GITHUB.RUN_NUMBER }}
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker container creation test
        run: |
          docker run -dt --name web1 niran736/intel5:tagname
          docker ps
